[project]
name = "crc2026-prelim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "panda>=0.3.1",
    "pytest>=9.0.0",
]

[tool.uv.workspace]
members = ["Prelim_special"]
